const fs = require('fs');
const zh = {
TREMADAN_IMAGE:"特雷马丹之影",BOUNCER_TILGAR:"门卫蒂尔加",BOUNCER_MASORA:"门卫玛索拉",SERGEANT_RAKKUS:"拉库斯军士",SERGEANT_TOEL:"托尔军士",SERGEANT_DAUKAR:"道卡军士",ARKADOS:"盲者阿卡多斯",NIRUH:"尼鲁",GRETA:"格蕾塔",ALCHEMIST_NIISA:"药剂师妮莎",ALCHEMIST_DOREA:"药剂师多蕾娅",BOATMAN_TIOM:"船夫蒂奥姆",TRADER_SARMA:"商人萨尔玛",ARMORER_DORMA:"护甲匠多玛",WEAPONSMITH_LOE:"铁匠勒伊",ROLGAM:"罗尔加姆",TRIBUNE_GELEB:"保民官格莱布",PRAETOR_RONGAE:"裁判官隆盖",BOATMAN_NOREAD:"船夫诺里德",TRADER_LIRDI:"商人莉尔迪",LADY_LEANNA:"莉安娜夫人",BROTHER_MIRTO:"米尔托修士",GOVERNOR_DAZLAN:"达兹兰总督",BISHOP_ARANDIR:"阿兰迪尔主教",ALCHEMIST_VLAZA:"药剂师弗拉扎",SISTER_MARIE:"玛丽修女",TROLL_COOK:"巨魔厨子",GIRL:"女孩",GUARDIAN_GOLEM:"守卫魔像",KINGSBRIDGE_INN:"桥畔少女",LANNEGAR_INN:"萨加尔歇脚处",JABAL_INN:"锈刃酒馆",RHONEIS_INN:"满盘酒馆",FOGAS_INN:"最后一火",SYDARUN_INN:"歌唱之井",NEWANTHUR_INN:"海员酒馆",NG_INN:"帝国客栈",NG_INN2:"绿骑士",FT_INN:"慷慨之王",FT_INN2:"勇武之王",NI_INN:"沉睡贵妇",NI_INN2:"神圣徽记",WEAPONSMITH_DOGUS:"铁匠多古斯",CHANCELLOR_NEBROS:"内布罗斯大臣",BROTHER_JANUS:"贾纳斯修士",SISTER_ARTA:"阿尔塔修女",BROTHER_GUDAZAR:"古达扎尔修士",SISTER_REMME:"蕾姆修女",SISTER_MADA:"玛达修女",BROTHER_GABRIEL:"加布里尔修士",MOTHER_COLLINS:"柯林斯嬷嬷",CAPTAIN_WRIGHT:"赖特队长",ALCHEMIST_MARKUS:"药剂师马库斯",WEAPONSMITH_SEVAE:"铁匠瑟薇",ALCHEMIST_MARELLE:"药剂师玛蕾尔",ARMORER_GOURD:"护甲匠古尔德",BOATMAN_ORRUS:"船夫奥鲁斯",TRADER_RONUS:"商人罗努斯",WEAPONSMITH_TERENA:"铁匠特蕾娜",BOATMAN_NARRIM:"船夫纳里姆",BOATMAN_MASON:"船夫梅森",TRADER_PINK:"商人平克",ARMORER_FLOYD:"护甲匠弗洛伊德",ALCHEMIST_TULL:"药剂师塔尔",VARSILIAN_KNIGHT:"瓦西利亚骑士",TRADER_WIELLE:"商人薇尔",ALCHEMIST_DRYONOS:"药剂师德莱奥诺斯",ORDUC_SOLLIGA:"索利加的奥杜克",ARMORER_REIA:"护甲匠蕾雅",MAN_BLACK:"黑衣人",TOWNSMAN:"镇民",GUARD:"卫兵",GUARDIAN:"守卫",CRATE:"木箱",FLOWER:"鲜花",CHEST:"箱子",MIRROR:"镜子",CORPSE:"尸体",BARREL:"木桶",FUNGUS:"菌类",THRONE:"王座",PRISONER:"囚犯",MAGIC_BARRIER:"魔法屏障",SIGNPOST:"路标",STAIRS:"楼梯",NEST:"巢穴",DOOR:"门",NOTICE:"告示",SEWER:"下水道",SARCOPHAGUS:"石棺",SHELF:"架子",HOLE_WALL:"墙上的洞",GOLDEN_TREE:"金树",BOOK:"书籍",STATUE:"雕像",WALL:"墙壁",BRAZIER:"火盆",TABLE:"桌子",LEVER:"拉杆",EIRAMA:"艾拉玛",RONAEF:"罗纳伊夫",JAILER:"狱卒",LEGION_DESERTER:"军团逃兵",LEGIONNAIRE_GNULBAM:"军团兵格努尔巴姆",DECURION_DESERTER:"什长逃兵",CAPTAIN_DEMETRIUS:"德米特里厄斯队长",CORDELIA:"考狄利娅",LEONATO:"里奥那托",BANQUO:"班柯",POLONIUS:"波洛涅斯",SPECTATOR:"观众",LAERTES:"雷欧提斯",TRADER_OPHELIA:"商人奥菲莉娅",ARMORER_ROSENCRANTZ:"商人罗森格兰兹",ALTAR_THREE:"三神祭坛",CAPTAIN_GUILDENSTERN:"盖登思邓队长",BROTHER_IAGUS:"伊阿古修士",JACHIMO:"贾奇摩",ALARBUS:"阿拉布斯",HERMIA:"赫米娅",ELLEIRA:"艾莱拉",GEBADI:"格巴迪",HOODED_MAN:"兜帽人",BAG:"布袋",GLUNK:"格伦克",BROGG:"布罗格",SULIDAR:"苏利达",TOMB:"墓碑",NICHE:"壁龛",BARAHID:"巴拉希德",TRADER_HARDIN:"商人哈丁",BLACKSMITH_DORNICK:"铁匠多尼克",TRADER_PIRENNE:"商人皮雷纳",BROTHER_PALVER:"帕尔弗修士",CAPTAIN_PELORAT:"佩罗拉特队长",BOATMAN_CLEON:"船夫克里昂",RANGER_VENABILI:"游侠薇娜比莉",SAGE_AMARYL:"贤者阿玛丽尔",BISHOP_BAYTA:"贝塔主教",MALLOW:"马洛",SELDON:"塞尔登",TRAINED_CAT:"受训剑齿猫",TRADER_NIBDAM:"商人尼布达姆",ARMORER_MORTHA:"护甲匠莫尔莎",SISTER_GENTA:"根塔修女",CAPTAIN_VLAD:"弗拉德队长",DEMONIC_ATTORNEY:"恶魔律师",ADMUS:"圣阿德穆斯",WOODSWOMAN:"樵妇",CAPTAIN_WHITEWATER:"怀特沃特队长",TERAM:"特拉姆",GUARD_CHEA:"守卫茜娅",ANTON_GERDT:"安东·格特",SHERYL:"雪莉尔",NISOR:"尼索",CAPTAIN_TEARA:"蒂亚拉队长",THEROD_NOM:"塞罗德·诺姆",ROLF_EHRAR:"罗尔夫·埃拉尔",DRUNKARD:"醉汉",MARGHERITE:"玛格丽特",
SULI:"苏莉",JIMEA:"吉梅娅",BETROTO:"贝特罗托",ROTVIC:"罗特维克",VILLAGER:"村民",RADAIM:"拉达伊姆",TEALA:"蒂雅拉",STORMKNIGHT:"风暴骑士",GILMOUR:"吉尔莫",LATIMER:"拉蒂默",'SIR_ANDREW_MASON':"安德鲁·梅森爵士",WATERS:"沃特斯",FRITHA_RHAYADER:"弗丽塔·拉亚德",BAFRAT:"巴弗拉特",THUG:"打手",BARRET:"巴雷特",SPICE_TRADER_JETHRO:"香料商杰思罗",TRAP_BEAR:"捕兽夹",TRAP_SPIKES:"尖刺陷阱",CASTLE_GUARD:"城堡卫兵",HORTON:"霍顿",WARRIOR:"战士",MINER:"矿工",OUTLAW:"法外之徒",OUTLAW_CHIEF:"法外之徒头目",VARANNARI_LEADER:"瓦兰纳里头人",MASTER:"大师",GRANDMASTER:"宗师",TRAVELLING_ARMORER:"行脚护甲匠",TRAVELLING_ALCHEMIST:"行脚药剂师",SHADY_TRAVELLER:"形迹可疑的旅人",ORC_COMMANDER:"兽人指挥官",TROLL_MARAUDER:"巨魔劫掠者",INITIATE_GLAYDAN:"初修士格莱丹",BUTTERFINGERS:"\"手滑\"",LILIANA:"莉莉安娜",DIRG_SWEETBLADE:"迪尔格·甜刃",GLARIUM:"格拉里姆",TORJA:"托尔雅",LORE_GUARDIAN:"求知守卫",RURAZAR:"鲁尔阿扎尔",TANGIR:"坦吉尔",AMARISA:"阿玛丽莎",DAREMA_BRIGHTHAMMER:"达蕾玛·明锤",FORSAKEN:"弃民",FRIGULD_INN:"第五阵风",VARANNARI:"瓦兰纳里人",STEEL_THUNDER:"钢雷",JARBAD:"贾巴德",CRUSADER:"圣战士",CAPTAIN:"队长",ALCHEMIST_VERA:"药剂师薇拉",ARMORER_HAN:"护甲匠韩",ZILDA:"席尔达",KALIS:"卡莉丝",CAPTAIN_DORSE:"多尔斯队长",CADUL:"卡杜尔",BODYGUARD:"贴身护卫",CHANCELLOR_MALARD:"马拉德大臣",MERCENARY:"佣兵",SPHERE:"球体",ACCOUNTANT:"账房",CLERK:"文书",ARCHBISHOP_DILLA:"迪拉大主教",BISHOP_BAREID:"巴雷德主教",FATHER_HADAR:"哈达尔神父",MAGICAL_BARRIER:"魔法屏障",TRADER_PHAZID:"商人法齐德",HIGH_PRIEST:"大祭司",INSCRIPTION:"铭文",OTHERWORLDLY_PRESENCE:"异界存在",TRADER_COLEEN:"商人柯琳",SERGEANT_MORG:"莫格军士",BOUNCER_TENDOR:"门卫腾多",ALTAR:"祭坛",SERGEANT_MAEVE:"梅芙军士",VALERAN:"瓦勒兰",CORRUPTED_MINOTAUR:"堕落的牛头人",ZOGARIS:"佐加里斯",SYXADRIS:"西萨德里斯",BASRUDAXUL:"长者巴鲁达克苏尔",FEVRESEE:"费芙蕾赛",
DERINA_GASHAM:"德莉娜·加沙姆",MONOLITH:"巨石",ROCKS:"岩石",CONSOLE:"控制台",ORACLE:"神谕机",ELEVATOR:"升降机",CALENDA:"卡伦达夫人",YAMiba:"亚米巴",YAMIBA:"亚米巴",PRAETOR_JENARD:"杰纳德裁判官",ROMENA:"罗梅娜",TASKMASTER_BREM:"监工布雷姆",ANGRY_GHOST:"怨灵",COUK:"库克",A_CORPSE:"一具尸体",CENTURION_KANUM:"百夫长卡努姆",DECURION_SARGOS:"什长萨尔戈斯",DARTOS:"达托斯",AGLARON:"阿格拉隆",MISARA:"米萨拉",ARCANE_KNIGHT:"奥术骑士",TRADER_JOHANNA:"商人约翰娜",ILEMMA:"艾莱玛",MEZIMER:"梅齐默",TRADER_GILRON:"商人吉尔隆",SOGARAD:"索加拉德",DORBUS:"多布斯",ARABELLE_WINTER:"阿拉贝尔·德温特",ICEMIST_INN:"魔法酒桶",WHITETOWER_INN:"失落的试剂",ALCHEMIST_MATOR:"药剂师马托",BREWER_TONEL:"酿酒师托内尔",BROTHER_DEFRERE:"德弗雷尔修士",ARMORER_VOCKJODI:"护甲匠沃克乔迪",ARMORER_TORDAM:"护甲匠托达姆",MIFADIS:"米法迪斯",ROSY:"罗西",RASMUND:"拉斯蒙德",CAPTAIN_TORDEN:"托登队长",FOLCARAD:"福尔卡拉德·白风暴",INSANE_WIZARD:"癫狂法师",WHITE_KING:"白王",PILGRIM:"朝圣者",BROTHER_HADRI:"哈德里修士",TRADER_GARNER:"商人加纳",C13_INN:"溺鼠酒馆",J7_INN:"银锚",TRADER_OTARAB:"商人奥塔拉布",TRADER_ORAC:"商人奥拉克",MESSENGER:"信使",SOLDIER:"士兵",RADIA:"拉迪娅",DOBROS_STORME:"多布罗斯·斯托姆",ANDRYS_STORME:"安德里斯·斯托姆",BED:"床铺",BLOOD_FOUNTAIN:"血泉",EIRENDA:"艾伦达",TRADER_DENTRA:"商人登特拉",BOATMAN_ELEDOR:"船夫埃莱多",CAPTAIN_CAREMA:"卡蕾玛队长",SERGEANT_TARBA:"塔尔巴军士",BAGADAR:"巴加达尔",GOVERNOR_TODBIR:"托德比尔总督",CONTRAPTION:"古怪装置",CAPTAIN_BALADIS:"巴拉迪斯队长",AZERAN:"阿泽兰",TRADER_GLYPHAX:"商人格里法克斯",CAPTAIN_SOROM:"索罗姆队长",K11_INN:"暴脾气元素",FOREMAN_DALLIS:"工头达利斯",THALASSOS:"塔拉索斯",GOLEM_TRADER:"魔像商",THREE_CLAWS:"三爪",STAR_SHADOW:"星影",LADY_MARISHA:"玛丽莎夫人",SIR_IROLIO:"艾罗利奥爵士",LAUGHING_DEER:"笑鹿",QUARTERMASTER:"军需官","VARESSA_GOLEM":"瓦蕾莎的魔像",BLAFARNE_PET:"布拉法恩的宠物",
};

function apply(path) {
  let text = fs.readFileSync(path, 'utf8');
  const lines = text.split('\r\n');
  let changed = 0, missed = [];
  const out = lines.map((line) => {
    if (!line.trim()) return line;
    const cols = line.split('\t');
    const tag = cols[0].trim();
    if (zh[tag] !== undefined) { cols[3] = zh[tag]; changed++; return cols.join('\t'); }
    if (tag !== 'tag') missed.push(tag);
    return line;
  });
  fs.writeFileSync(path, out.join('\r\n'), 'utf8');
  console.log(path, 'updated', changed, 'missed:', missed.join(', ') || 'none');
}
apply(process.argv[2]);
