const fs = require('fs');
const zh = {
VAULT_COST:'购买这个魔法保险库需要 {COST} 金币。',
VAULT_BUY:'你愿意花 {COST} 金币购买这个永久魔法保险库吗？',
VAULT_DESC:'魔法保险库可以存放你的物品。你可以在任何市政厅使用它。',
TH_FINE_CONFIRM:'只要 [BLUE]{FINE} 金币[]，官员们就可以仁慈地移开视线，忘掉你的一些罪行。你同意吗？',
TH_LABEL_AVERAGE:'（[BLUE]{1}[] 与 [BLUE]{2}[] 声望的平均值）',
CONFIRMATION_OVERWRITE_GAME:'你确定要用新游戏覆盖这个存档吗？',
SLOTS_HELP:'游戏将从你最近的存档恢复。如果你想读取自动存档（上次休息）或其他存档，请点击黄色文件夹按钮。',
WARRIOR_DESCRIPTION:'一线作战的斗士，几乎能使用所有武器和护甲。[BLUE]（了解更多）[]',
ROGUE_DESCRIPTION:'阴险而致命，盗贼能造成大量伤害，并拥有多样的技能组合。[BLUE]（了解更多）[]',
CLERIC_DESCRIPTION:'受三神祝福的强大战地牧师。对亡灵有极大的克制。[BLUE]（了解更多）[]',
MAGE_DESCRIPTION:'该职业目前不可用',
DL_DESC_CASUAL:'与"普通"相同，但闲置时恢复少量生命，并可在地牢中快速存档。简单。',
DL_DESC_NORMAL:'对多数玩家来说恰到好处的挑战。世界充满敌意，遭遇战十分危险。',
DL_DESC_HARD:'敌人与陷阱更强、更多。为硬核 RPG 玩家设计。',
DL_DESC_IRONMAN:'与"困难"相同，但除退出游戏外无法存档。死亡即终局。',
SPEND_ALL_TRAITS:'你必须用完所有属性点才能继续。',
SPEND_ALL_SKILLS:'你必须用完所有技能点才能继续。',
TOO_TIRED_RECOVER:'你太累了，无法恢复。找个安全的地方睡觉吧',
NOT_INJURED:'你没有受伤，不需要恢复',
ENEMIES_AROUND:'附近有敌人时无法恢复',
ENEMIES_AROUND_HIDE:'附近有敌人时无法潜行',
NOT_VERY_INJURED:'你的伤势并不重，确定要恢复全部生命吗？',
CHOOSE_OPTION_CONTINUE:'选择一个选项以继续',
RECOVER_ALL_HEALTH:'你休息了 12 小时，恢复了全部生命。<p>游戏已保存',
RECOVER_SOME_HEALTH:'你休息了 6 小时，恢复了一些生命。<p>游戏已保存',
RECOVER_ALL_HEALTH_NOSAVE:'你休息了 12 小时，恢复了全部生命。',
RECOVER_SOME_HEALTH_NOSAVE:'你休息了 6 小时，恢复了一些生命。',
GAME_SAVED:'游戏已保存',
GAME_QUICKSAVED:'快速存档成功',
INTRO_1:'千百年来，安多里亚大陆在大帝国的旗帜下统一而繁荣。',
INTRO_2:'仿佛帝国将永世长存，永远强大、和平，科学与艺术欣欣向荣。',
INTRO_3:'但每个帝国都终将陨落',
INTRO_4:'一个世纪前，深渊领主崛起了。传说这些神秘的咒法师来自另一个世界。他们打开了魔法之门，恐怖之物由此蜂拥而出。',
INTRO_5:'恐怖之物究竟是什么、长什么模样，早已无人记得。但短短几周，帝国便在其全部伟力之下沦陷。',
INTRO_6:'只有数千人幸存，乘船逃往瓦兰纳尔岛。那是帝国的一块殖民地，一片野蛮而严酷的土地。所幸，恐怖之物没有追来。',
INTRO_7:'这些流亡者历尽艰辛，某种程度上驯服了这片土地。他们建起农场、村庄、城市和城堡。终于——',
INTRO_8:'放逐王国',
INTRO_9:'一个世纪后，对许多人来说，帝国与恐怖之物不过是童话。作为年轻的冒险者，你更担心的是没活儿干、钱袋空空……',
INTRO_10:'但你的运气变了。你收到一封来自新加兰德的魔法信件，召你去领取一笔神秘的遗产。听起来大有可为！',
INTRO_11:'你不记得在那里有什么亲戚，但你还是启程了。在穿越险恶的萨加尔森林时，你听到前方传来令人不安的声响……',
INITIAL_MESSAGE_TITLE:'我在睡梦中被抢劫了！',
INITIAL_MESSAGE:'一切都没了：钱、武器，连那封信也不见了。现在我只有一把匕首和几枚硬币。一定是阿达昂干的！<p><p>我必须重新武装自己，否则活不了多久。也许可以去北边那个村子找找帮助。',
DRINK:'你在酒馆里消磨了几个小时，一边喝酒，一边竖着耳朵打听消息和传闻。',
DRINK_FAIL:'你没打听到什么有意思的事。',
DRINK_SUCCESS_LOCATION:'你打听到的消息是关于',
DRINK_SUCCESS_LOCATION2:'它位于',
INN_GOSSIP_POSSIBLE:'周围有不少酒客可以跟你碰杯闲聊。也许能听到有用的传闻。',
INN_GOSSIP_IMPOSSIBLE:'这里的人你都聊过了，故事也都听遍了。改天再来认识新朋友吧。',
'ARCH-ENEMY_DESC':'你在这里深受憎恨，被视为 #REPUTATION#。',
ENEMY_DESC:'你在这里受人憎恨，被视为 #REPUTATION#。',
CRIMINAL_DESC:'你在这里被人仇恨，被视为 #REPUTATION#。',
BANDIT_DESC:'你在这里不受信任，被视为 #REPUTATION#。',
RASCAL_DESC:'你在这里不被信任，被视为 #REPUTATION#。',
UNKNOWN_DESC:'你在这里是 #REPUTATION#，你的存在基本无人理会。',
FRIENDLY_DESC:'你在这里被视为 #REPUTATION#，人们以礼相待。',
TRUSTED_DESC:'你在这里被视为 #REPUTATION#，人们以礼相待。',
HERO_DESC:'你在这里被视为 #REPUTATION#，大多数人见到你都满怀敬意。',
GREAT_HERO_DESC:'你在这里被视为 #REPUTATION#，大多数人见到你都满怀敬佩与敬畏。',
LEGENDARY_HERO_DESC:'你在这里是 #REPUTATION#，所有人微笑着向你致以深深的敬意。',
AREA_UNAVAILABLE_TITLE:'该区域在游戏中尚未开放<p>',
AREA_UNAVAILABLE:'该区域尚未加入《放逐王国》，但可能会在未来的更新中推出！',
REPUTATION_CHANGED:'你的声望发生了变化',
HELP_TITLE:'学习游戏操作',
HELP_SECTION_MOVING:'提示：手柄与攻击按钮',
HELP_MOVING:'战斗很简单：只需[BLUE]按住攻击按钮[]，你就会全速攻击。不必快速连点……除非那样让你觉得更带劲。<p><p>攻击时，如果你没有面向敌人，会[BLUE]自动转向[]范围内最近的敌人。',
HELP_SECTION_CHARACTER:'提示：你的角色、技能与属性',
HELP_CHARACTER:'[BLUE]左上角[]的按钮会打开角色属性和装备。记得去那里分配[BLUE]属性点和技能点[]，不然日子会很难过。<p><p>头像旁边的大红条是你的生命值，小黄条是升到下一级的进度。',
HELP_SECTION_INTERACTION:'提示：与世界互动！',
HELP_INTERACTION:'还记得他们教过你不要和陌生人说话、不要捡地上的东西吗？好吧，在这个游戏里你不但可以，而且还应该。<p><p>靠近人物或物品时，屏幕[BLUE]右上角[]会出现一个按钮。点击它即可互动。',
HELP_SECTION_HEALING:'提示：治疗与恢复',
HELP_HEALING:'左边的恢复按钮会[BLUE]完全治愈你[]。很棒吧？但它每天只能使用[BLUE]有限的次数[]。之后你就需要[BLUE]在客栈睡觉[]了。<p><p>在客栈休息会完全恢复你的恢复按钮。',
HELP_SECTION_INN:'提示：睡觉与保存游戏',
HELP_INN:'你需要[BLUE]在客栈睡觉[]来重置恢复按钮。而且睡觉时，[BLUE]游戏会自动保存[]。在城镇里找一扇带有客栈标志的门吧。<p><p>如果你需要马上关闭或最小化游戏，它会自动保存。',
HELP_SECTION_SAVE:'保存游戏',
HELP_SAVE:'现在是[BLUE]保存游戏[]的好时机。《放逐王国》相当致命，所以经常存档！<p><p>点击屏幕下方的[BLUE]快速存档按钮[]，或在设置界面查看更多选项。记住，[BLUE]在地牢里[]，只有退出时才能存档。',
HELP_SAVE_CASUAL:'现在是[BLUE]保存游戏[]的好时机。《放逐王国》相当致命，所以经常存档！<p><p>点击屏幕下方的[BLUE]快速存档按钮[]，或在设置界面查看更多选项。',
HELP_STATS:'角色属性',
HELP_DAMAGE:'[BLUE]+{1h}[] 单手武器<p>[BLUE]+{2h}[] 双手武器<p>[BLUE]+{l}[] 轻武器<p>[BLUE]+{r}[] 远程武器',
PERCEPTION:'感知',
HELP_PERCEPTION:'[BLUE]{per}%[] 发现秘密的概率。',
DEVICES:'拆除装置',
HELP_ALCHEMY:'[BLUE]{alc}%[] 炼制药剂的基础概率。',
ALCHEMY:'炼金',
HELP_SMITHING:'[BLUE]{smi}%[] 锻造物品的基础概率。',
SMITHING:'锻造',
HELP_DEVICES:'[BLUE]{dev}%[] 解除陷阱的概率。',
TIT_GOSSIP:'情报',
HELP_GOSSIP:'[BLUE]{gos}%[] 打听传闻的概率。',
HELP_CRITICAL:'你打出暴击的概率，以及暴击时的伤害倍率。多个技能可以影响这个数值。',
HELP_DPS:'每秒伤害。它是用上面三个数值计算出的、持续攻击时该武器能造成的伤害。但不计入目标的护甲与抗性。',
HELP_ARMOR:'所有物理攻击对你减免 {ARMOR-VALUE} 点伤害。',
HELP_ARMOR_ARROWS:'所有投射物攻击额外对你减免 {ARMOR-VALUE} 点伤害。',
HELP_RESISTANCES:'抗性能减少某些特殊类型的伤害，这类伤害通常来自魔法。抗性可以通过装备提升，在高等级面对特定遭遇时会变得非常重要。每种抗性都是独立数值：火焰、冰寒、电击、死亡、毒素和神圣。',
CHARACTER_CLASSES:'角色职业',
CLASS_DESC_WARRIOR:'他们可以是野蛮的莽夫、老练的佣兵，或优雅的骑士。但共同点是：他们能使用[BLUE]最重的护甲和武器[]，而且总是容易卷入麻烦。<p><p>战士拥有全职业[BLUE]最高的生命值[]和可观的伤害成长。他们的技能多以防御为主，配合重甲让他们能在与大量怪物的正面交锋中存活。嗯，至少比别人撑得久！<p><p>必要时，他们可以牺牲部分防御改用[BLUE]双手武器[]，对付高护甲敌人效果拔群。除少数例外，只有战士能用双手武器。<p><p>[BLUE]1 级基础生命[]：45hp<p>每级生命成长：+6hp',
CLASS_DESC_ROGUE:'如果世界不公……你何必讲道理？盗贼占尽一切便宜，并尽可能规避所有风险。最好从背后偷袭，在最料想不到的时刻出手。哪怕用[BLUE]远程武器[]——他们同样精通。对，盗贼就是这么干活的。<p><p>盗贼深知如何伤人。他们的[BLUE]近战伤害高于任何其他职业[]，技能让他们[BLUE]隐匿行踪[]或打出额外伤害，特别擅长刺杀头目和施法者。但他们的生命不多，好甲也难寻。<p><p>[BLUE]1 级生命[]：30hp<p>每级生命成长：+4hp<p>[BLUE]近战伤害[]获得 [BLUE]+1[] 加成，6、12、18、24 级再次提升。<p>[BLUE]其他优劣[]：盗贼感知 +20%，解除陷阱与锁 +20%，情报 +10%。',
CLASS_DESC_CLERIC:'被三神拣选为祭司的人拥有强大的力量。没人知道为什么，但有些孩子一出生，神明便对他们微笑，赐予他们掌管生死的奇异权能。他们能[BLUE]治疗[]、施展[BLUE]防护魔法[]，或用烈焰[BLUE]重击敌人[]。他们对[BLUE]亡灵尤为克制[]。许多人献身侍奉三神、救助困苦之人，也有人选择更自私的道路，以冒险者或佣兵为生。所幸三神似乎并不介意。<p><p>牧师几乎可以穿[BLUE]任何护甲[]，但武器选择有限，因此通常伤害[BLUE]低于战士或盗贼[]。<p><p>[BLUE]1 级生命[]：35hp<p>每级生命成长：+5hp<p>[BLUE]法力[]：12，每级+2<p>[BLUE]其他优劣[]：传说牧师若悖逆三神，将失去神力。',
LEARN_MORE:'我可以在酒馆喝酒聊天，多打听些事情。',
RECRUITED_COMPANION_TITLE_MALE:'你招募了一位同伴！！！',
RECRUITED_COMPANION_MALE:'从现在起，他会跟随你冒险，或在他的家乡等你再次邀请。他不会死于战斗，你可以放心为他装备并让他升级。<p><p>同伴随行时，你获得的经验减少 20%，但他也会获得一些经验。',
RECRUITED_COMPANION_TITLE_FEMALE:'你招募了一位同伴！！！',
RECRUITED_COMPANION_FEMALE:'从现在起，她会跟随你冒险，或在她的家乡等你再次邀请。她不会死于战斗，你可以放心为她装备并让她升级。<p><p>同伴随行时，你获得的经验减少 20%，但她也会获得一些经验。',
DISCONNECTED_GPLAY:'[BLACK]你[RED]未连接[] [BLUE]Google Play 游戏[]。游玩期间无法获得成就和排行榜积分。[]',
CONNECTED_GPLAY:'[BLACK]你已[GREEN]连接[] [BLUE]Google Play 游戏[]。成就和排行榜功能正常。[]',
DISCONNECTED_GPLAY_CLOUD:'[BLACK]你[RED]未连接[] [BLUE]Google Play 游戏[]。无法从云端保存或恢复存档。[]',
CONNECTED_GPLAY_CLOUD:'[BLACK]你已[GREEN]连接[] [BLUE]Google Play 游戏[]。云端保存与恢复已启用。[]',
DISCONNECTED_GPLAY_IOS:'[BLACK]要使用成就和排行榜，你需要登录 Play Games 服务。[]',
CONNECTED_GPLAY_IOS:'[BLACK]成就和排行榜已启用。[]',
DISCONNECTED_GPLAY_CLOUD_IOS:'[BLACK]要在云端保存或恢复游戏，你需要登录 Play Games 服务。[]',
CONNECTED_GPLAY_CLOUD_IOS:'[BLACK]现在可以从云端保存或恢复游戏了。[]',
GPLAY_INFO_CONFIRM:'要启用[BLUE]成就[]、[BLUE]排行榜[]和可选的[BLUE]云端存档[]，需要登录 Play Games 服务。现在登录吗？',
BACKUP_REMINDER:'提醒：如果你卸载游戏，存档将会丢失。要妥善保管或在其他设备上游玩，请使用[BLUE]继续游戏[]菜单中的[BLUE]导出与云存档[]功能。',
BACKUP_INFO_TEXT:'[MAROON]使用以下选项可以把存档转移到其他设备或妥善保管。你可以手动[BLUE]导出到文件[]，或通过[BLUE]云端[]自动进行。[]',
BACKUP_INFO_FILE_TEXT:'[BLUE]使用文件：[] 存档将导出到手机存储根目录的 EK.bak 文件。可以从同一位置（或安卓的 Download 文件夹）恢复。',
BACKUP_INFO_FILE_TEXT_ANDROID:'[BLUE]使用文件：[] 游戏可以从 android/data/net.fdgames.ek.android/files 目录下的 EK.bak 文件导出或读取数据。[RED]注意！卸载应用时该目录会被安卓删除[]，请先复制到别处。',
BACKUP_INFO_FILE_TEXT_IOS:'[BLUE]使用文件：[] 数据将导出到游戏 Documents 目录下的 EK.bak 文件。你可能需要第三方工具（如 iExplorer）访问它。',
BACKUP_INFO_CLOUD_TEXT:'[BLUE]保存到云端：[] 数据将保存到你的 Google Play Games 账户。建议定期使用，作为游戏的安全备份。',
BACKUP_INFO:'把全部存档导出到文件 ##BACKUP## 吗？',
BACKUP_RESTORE_NOFILE:'无法执行此操作：找不到文件 ##BACKUP##。',
BACKUP_RESTORE_CONFIRM:'从文件 ##BACKUP## 恢复存档，并覆盖当前存档吗？',
BACKUP_RESTORE_CLOUD_CONFIRM:'从云端恢复存档，并覆盖当前存档吗？',
BACKUP_DONE:'备份已成功保存到文件 ##BACKUP##。',
BACKUP_RESTORED:'备份恢复成功。',
BACKUP_FAILED:'操作未能完成。',
CLOUD_UPLOAD_OK:'数据已成功保存到云端。',
CLOUD_DOWNLOAD_OK:'数据已从云端成功恢复。',
CLOUD_ERROR:'操作失败。错误代码：{e}',
DESC_STR:'体魄之力，搬举重物、施加伤害的能力。主要效果是提高[BLUE]近战伤害[]，同时也增加生命。',
DESC_END:'健康、耐痛与坚持的能力。这项属性主要决定你的[BLUE]生命值[]，是生存的根本。',
DESC_AGI:'协调、速度、平衡与手眼灵巧。这是一项用途广泛的全能属性。',
DESC_INT:'推理、记忆、学习与思考的能力。对法师而言最重要的是它决定[BLUE]法力值[]。<p>它还可能解锁新的[BLUE]对话[]选项。',
DESC_AWA:'感知，即能否察觉周围的细微变化。它可能解锁新的[BLUE]对话[]选项。',
DESC_PER:'对人性人心的洞察，以及自制与专注。它决定牧师的[BLUE]法力值[]，并常常解锁新的[BLUE]对话[]选项。',
DESC_STR_STATS:'» 每 1 点力量：[BLUE]单手武器[]伤害 +1<p>» 每 1 点力量：[BLUE]双手武器[]伤害 +1.5<p>» 每 1 点力量：轻武器伤害 +0.5<p>» 每 [BLUE]2 点[]力量：每级生命 [BLUE]+1[]',
DESC_END_STATS:'» 每 1 点耐力：基础生命 [BLUE]+5[]<p>» 每 1 点耐力：每级生命 [BLUE]+1[]<p>» 每 1 点耐力：毒素抗性 [BLUE]+5[]',
DESC_AGI_STATS:'» 每 1 点敏捷：[BLUE]护甲 +1[]<p>» 每 1 点敏捷：[BLUE]轻武器[]与[BLUE]远程武器[]伤害 +1<p>» 每 1 点敏捷：[BLUE]单手武器[]伤害 +0.5<p>» 每 1 点敏捷：[BLUE]陷阱与开锁[]概率 +5%',
DESC_INT_STATS:'» 每 1 点智力：[BLUE]法师[]每级法力 [BLUE]+1[]<p>» 每 1 点智力：经验获取 [BLUE]+2%[]<p>» 每 2 点智力：[BLUE]牧师[]每级法力 [BLUE]+1[]<p>» 每 2 点智力：[BLUE]陷阱与开锁[]概率 +5%<p>» 每 2 点智力：[BLUE]感知[]概率 +5%',
DESC_AWA_STATS:'» 每 1 点感知：[BLUE]感知[]概率 +5%<p>» 每 2 点感知：[BLUE]情报[]概率 +5%<p>» 每 [BLUE]3 点[]感知：[BLUE]护甲 +1[]<p>» 每 2 点感知：[BLUE]远程武器[]伤害 +1',
DESC_PER_STATS:'» 每 1 点魅力：[BLUE]牧师[]每级法力 [BLUE]+1[]<p>» 每 2 点魅力：[BLUE]法师[]每级法力 [BLUE]+1[]<p>» 每 1 点魅力：[BLUE]情报[]概率 +5%<p>» 每 1 点魅力：[BLUE]精神[]抗性 +2、[BLUE]死亡[]抗性 +5',
DESC_STR_0:'跟普通小孩一样壮。你还是个孩子，对吧？',
DESC_STR_1:'恶霸们总算会去找别人下手了。',
DESC_STR_2:'你这一身腱子肉明摆着就是干实事的人。',
DESC_STR_3:'可以跟牛头人掰手腕。虽然你还是会输。',
DESC_STR_4:'可以跟牛头人掰手腕，而且有机会赢。',
DESC_STR_5:'超人的力量。很难找到能装下那二头肌的衣服。',
DESC_END_0:'毫无疑问，你需要练练。',
DESC_END_1:'你的身子骨还不算太糟。',
DESC_END_2:'你能吃苦受累，还能一直走下去。',
DESC_END_3:'你"不死小强"的本事越来越强了。',
DESC_END_4:'你可以跟兽人拼酒量了。',
DESC_END_5:'你就是钢筋铁骨，几乎杀不死。',
DESC_AGI_0:'你走路基本不会绊倒。大部分时候。',
DESC_AGI_1:'身手还算利索。有时你能在危险中脱身。',
DESC_AGI_2:'协调性不错，还能玩两下杂耍。只是别用刀子玩。',
DESC_AGI_3:'你会翻筋斗、倒立行走……可以考虑去马戏团发展。',
DESC_AGI_4:'你能从猴子手里偷走香蕉。',
DESC_AGI_5:'你仿佛漂浮着移动。你和凡人的走路方式都不一样。',
DESC_INT_0:'你可不是地牢里最亮的火把，对吧？',
DESC_INT_1:'你的智力平平。抱歉，总得有人告诉你。',
DESC_INT_2:'你是村里的天才。恭喜。',
DESC_INT_3:'你聪明到能意识到自己其实没那么聪明。',
DESC_INT_4:'你的记忆力和推理能力常常把人吓一跳。',
DESC_INT_5:'你在这世界上感到孤独。非常孤独。',
DESC_AWA_0:'那是什么？你周围的世界总是模糊又费解。',
DESC_AWA_1:'你学会了眼观六路耳听八方。早该如此。',
DESC_AWA_2:'眼尖耳灵……周围发生的事你大多能察觉。',
DESC_AGA_PLACEHOLDER_:null,
DESC_AWA_3:'打牌时想骗你非常难。倒也不是完全不可能。',
DESC_AWA_4:'想瞒过你几乎是不可能的事。',
DESC_AWA_5:'对你来说，一切都一览无余。',
DESC_PER_0:'为什么大家都讨厌你？',
DESC_PER_1:'你通常记得对人微笑。',
DESC_PER_2:'你交朋友从来不费劲。',
DESC_PER_3:'你懂得如何鼓舞和影响他人。',
DESC_PER_4:'"你总是鹤立鸡群；人们常常向你请教。"',
DESC_PER_5:'没有什么能阻止你，而且所有人都知道。',
TRAIT_UPGRADE_MESSAGE:'你愿意花 #COST# 点来提升这项属性吗？',
FREE_FEATURE_0:'可用区域：[BLUE]30 个[]。',
FREE_FEATURE_1:'等级上限：[BLUE]8 级[]。',
FREE_FEATURE_2:'可用职业：战士、盗贼。',
FULL_FEATURE_0:'一次性买断（{p}），解锁完整游戏。',
FULL_FEATURE_1:'[BLUE]146 个区域[]、[BLUE]97 个任务[]，外加 200 多个市政厅任务。',
FULL_FEATURE_2:'职业：战士、盗贼、牧师、法师。',
LICENSE_INFO:'《放逐王国》目前处于 [BLUE]测试阶段[]。它已提供巨大的世界和众多任务，但少数内容尚未完工。我们会持续加入新内容与新功能，感谢你的支持！',
LICENSE_INFO_IOS:'《放逐王国》是一个持续成长壮大的[BLUE]开放世界[]。请在下方查看当前[BLUE]可用的区域与可完成的任务[]。感谢你的支持！',
ONLY_PLACE_FULL_LICENSE:'你要访问的功能或地点仅限[BLUE]完整版[]。想了解更多并解锁吗？<p><p>',
ONLY_XP_FULL_LICENSE:'你的角色已达[BLUE]免费版[]的经验上限。想了解更多并解锁此限制吗？<p><p>',
CODE_WORKED:'恭喜！你的激活码已成功启用。',
CODE_FAILED:'很遗憾，你输入的激活码无效。请检查网络连接，或联系我们。',
MAX_XP:'已达免费版经验上限',
RESTORING_LICENSE:'正在尝试恢复之前购买的授权。可能需要几分钟。',
WARNING_MEMORY:'"[RED]警告[]：检测到内存不足 1GB；你的设备[BLUE]可能不兼容[]。游戏可能随时崩溃，我们无法修复。"',
WARNING_STORE:'[RED]警告[]：你的 [BLUE]Google Play 商店[]版本可能过旧，或因某些原因无法访问。如果反复出现，可能无法进入商店页面。',
RATING_TEXT:'愿意现在为《放逐王国》评分吗？评分和评论真的能让游戏变得更好。',
NAME_LENGHT:'角色名字的长度必须在 3 到 20 个字符之间！',
CHOOSE_SLOT_BUTTON:'选择一个快捷栏位',
CHOOSE_SLOT_SLOT:'要指派物品，请点击物品栏或背包中的栏位',
MESSAGE_ITEM_COOLDOWN:'每 3 秒游戏时间只能使用一件物品。',
MESSAGE_ITEM_COOLDOWN_NORMAL:'每 2 秒游戏时间只能使用一件物品。',
MISSED_MESSAGE:'敌人靠得太近，你的箭射空了！',
GAINED_LORE:'你学到了重要的知识，变得更有阅历了。',
DESC_ITEM_ORCSLAYER:'攻击兽人时，[BLUE]+{r}[] 伤害。',
DESC_ITEM_HOLY:'攻击亡灵时，[BLUE]+{r}[] 伤害。',
DESC_ITEM_BANISHING:'攻击异界生物（恶魔、元素生物等）时，[BLUE]+{r}[] 伤害。',
DESC_ITEM_BEASTSLAYER:'攻击野兽与半兽生物时，[BLUE]+{r}[] 伤害。',
DESC_ITEM_VICIOUS:'攻击生命低于 30% 的敌人时，[BLUE]+{r}[] 伤害。',
DESC_ITEM_PARALYSIS1:'攻击敌人时，有 6% 概率将其麻痹 5 秒。',
DESC_ITEM_STUN1:'攻击敌人时，有 5% 概率将其眩晕 2 秒。',
DESC_ITEM_STUN2:'攻击敌人时，有 10% 概率将其眩晕 2 秒。',
DESC_ITEM_SLOW1:'攻击敌人时，有 6% 概率使其迟缓 6 秒。',
DESC_ITEM_STABILITY:'穿戴此物品时，你免疫击退。',
DESC_ITEM_WISDOM:'获得 [BLUE]+{r}% 经验[]（向上取整）。',
DESC_ITEM_STUNIMMUNITY:'穿戴此物品时，你免疫[BLUE]眩晕[]，且[BLUE]麻痹[]效果持续时间减半。',
DESC_ITEM_VORPAL:'每级 5% 概率在暴击时造成致命重创。与"重度暴击"技能叠加。',
DESC_ITEM_GOSSIP:'此物品使你在客栈打听新传闻与消息的概率提高 [BLUE]+{r}[]%。',
DESC_ITEM_DETECTION:'此物品使你发现隐藏物（如陷阱或暗门）的概率提高 [BLUE]+{r}[]%。',
DESC_ITEM_TINKERING:'此物品使你拆除陷阱或其他装置的概率提高 [BLUE]+{r}[]%。',
DESC_ITEM_SILVER:'白银武器对狼人和其他抗普通伤害的变形生物造成[BLUE]全额伤害[]。',
DESC_ITEM_SHIELD:'每次受击减免护甲值的 40-100%，而非 20-100%。',
DESC_ITEM_OFFHAND:'为左手平衡设计，提供额外攻击加成，但不作为盾牌计算。',
HELP_ATTRIBUTE_ITEM:'你装备了一件提升[BLUE]属性[]的物品。恭喜！<p><p>记住，与其他加成不同，这类效果不会叠加。如果再找到提升同一属性的物品，只有最高的那个生效。',
HELP_SECTION_ATTRIBUTE_ITEM:'提升属性的物品',
MSG_ITEM_NOT_STACK:'你装备了多件提升同一属性的物品！只有最高的一个生效！',
SLEEP_CONFIRM:'你想睡 12 小时并完全恢复吗？',
WARNING_SNEAK:'[BLUE]偷袭[]技能现在从背后攻击敌人时真正生效，并附带眩晕。该技能已重置。',
WARNING_WHIRLWIND:'"[BLUE]旋风斩[]技能的眩晕概率已下调；我们重置了该技能并返还了你的技能点。"',
WARNING_CLEAVE:'"[BLUE]顺劈[]技能现在有目标数上限；我们重置了该技能并返还了你的技能点。"',
WARNING_SHARDS_TITLE:'托尔之眼已集齐！',
WARNING_SHARDS:'"随着神器重归完整，碎片将不再掉落，已有的碎片也会消失。<p><p>你仍可完成与回收碎片相关的任务，但不会再从中获得碎片。"',
DONATE_TEXT:'感谢支持本游戏！！！如果你愿意捐款，能让《放逐王国》[BLUE]更大更好[]，并支持我们开发更多[BLUE]老派 RPG 游戏[]。',
DONATE_THANKS:'我们收到了你的捐款，它会很快变成更多冒险。谢谢！！！',
MSG_CANT_CHANGE_LANGUAGE:'游戏进行中无法更改此设置。请回到主菜单再选择。',
WARNING_LANG_CHANGED_SLEEP:'如果你读取用其他语言保存的游戏，部分名称在角色于客栈休息前不会翻译。',
WARNING_LANG_CHANGED_RESTART:'游戏即将关闭，以使更改生效。',
WARNING_LANG_INCOMPLETE:'此翻译仍在进行中，部分文本可能显示为英文。你仍要切换语言吗？',
WARNING_CONTROLLER:'未检测到外部手柄。',
INFO_CONTROLLER:'游戏支持[BLUE]部分[]手柄功能。某些操作仍需使用触屏。',
TOL_CURSE_LOG:'托尔的诅咒正在吸取你的生命！',
TOL_CURSE_MSG:'这顶王冠掌握着凌驾生死的古老力量，会不断吸取你的生命，直到你变成幽灵。<p><p>丢弃或存入仓库都无法破除诅咒，唯一的希望是有人自愿从你手中接过它。',
SKILL_POINT_GAINED:'获得技能点！',
WARNING_CONTAINER:'警告：你把一件重要物品留在了那个容器里。记住，区域刷新后，物品可能永远消失。',
WARNING_DROPPED:'一件重要的任务物品因你的背包已满而掉落在地。你应该把它捡起来。',
WARNING_START_LANG_INCOMPLETE:'提醒：此翻译仍在进行中，部分文本可能显示为英文。',
DESC_ITEM_EMP:'[BLUE]{r}% 概率[]消耗一块[BLUE]远古电池[]，造成大量电击伤害（并可麻痹机器人）。',
DESC_ITEM_ANTIRAD:'能部分保护你免受灰烬荒原中漂浮的诡异发光粒子的侵害。',
MSG_LETTER_ARK_TITLE:'一封魔法信件在你手中显现！',
MSG_LETTER_ARK:'"它与你多年前收到的遗产信非常相似；毫无疑问，这封信同样来自特雷马丹之塔。<p><p>信上只有一句话：\'来塔里，我找到了洛塔桑方舟的位置！\'。你刚一读完，字条便消散了。"',
ENDING_1:'"仅仅几天之后，你就意识到任务失败了，人类在劫难逃。一座座城镇接连沦陷，最终无处可逃；在与恐怖之物的壮烈最后抵抗中，你献出了生命。"',
ENDING_2:'"你穿过深渊之门，追寻永生与新世界无尽冒险的许诺；但那是另一个尚未讲述的故事。也许有一天，被恐怖之物吞噬的垂死世界的噩梦终将消散……"',
ENDING_3:'"你及时冲出方舟，看见逃生舱以惊人的速度升空。一道比太阳还耀眼的爆炸标志着深渊之门的毁灭，也标志着你的胜利。恭喜你，拯救了世界！"',
WIKI_CONFIRM:'此选项将打开[BLUE]《放逐王国》Wiki[]，一个粉丝站点（仅英文），有详尽资料、攻略和剧透。要访问吗？',
MAGE_DESCRIPTION2:'献身奥术之人。脆弱，但终将无比强大。[BLUE]（了解更多）[]',
CLASS_DESC_MAGE:'"极少数人生来拥有魔法天赋，而其中能从法师基础训练中活下来的更少。法师凭借多种[BLUE]攻击法术[]驾驭强大的毁灭之力，也在有限程度上掌握一些防御能力。王国里许多年轻法师四处游荡，寻找足以让他们名扬四海、加入著名法师公会的古代遗迹和奥术秘密；很多时候，他们贪多嚼不烂。因此平民百姓眼里，他们名声就是个惹事精。<p><p>法师[BLUE]不能穿戴大多数护甲[]，但可以用长袍增强力量并获得轻微保护。武器方面可使用能快速施放魔法攻击的[BLUE]魔杖[]，或更强力的[BLUE]法杖[]。<p><p>[BLUE]1 级生命[]：23hp<p>每级生命成长：+3hp<p>[BLUE]法力[]：12，每级+2"',
DESC_ITEM_ARCANE:'此武器每次攻击需消耗 [BLUE]{r} 点法力[]。',
HELP_SECTION_ITEMS:'提示：带特殊属性的物品',
HELP_ITEMS:'有些物品名字下方有一个蓝色词语。[BLUE]点击它[]可以了解其特殊属性。<p><p>比如，那个箱子里的圆盾就有[BLUE]盾牌[]属性。想了解具体效果，就点那个蓝色词。',
HELP_SECTION_DUNGEON:'提示：你正处于地牢',
HELP_DUNGEON:'在室内探索要格外小心，这里的危险更甚。此区域内[BLUE]无法保存游戏[]。<p><p>不过如果需要退出游戏，不必担心进度。点开选项，选择[BLUE]保存并退出[]，之后就能继续冒险。想在任何地方存档，可以用[BLUE]休闲[]难度重新开始。',
WARNING_MAGE_DEVELOPMENT:'法师职业仍在开发与深度测试中。确定要以法师游玩吗？',
HELP_SECTION_RELOAD:'提示：从不同存档读取',
HELP_RELOAD:'你有多个存档可用，以防刚死就快速存档或被困。客栈睡觉时会有一个[BLUE]自动存档[]，无法覆盖。<p><p>在[BLUE]继续游戏[]菜单点击[BLUE]黄色文件夹[]按钮即可访问。另外在选项/保存游戏菜单里还有两个额外存档栏位。',
SETTINGS_OLD_FONTS:'使用简易字体。重启游戏后生效。',
SETTINGS_SHOW_NUMBERS:'在生命/法力条上显示数字',
SETTINGS_TOUCHGO:'启用"点按移动"输入',
WARNING_FONTS:'游戏字体已改进。可在设置菜单换回旧版。',
LOG_MAGE_ARMOR_TRAP:'法师护甲偏转了一个陷阱并随之消散',
BOSS_TEXT:'据说最近有人目击到一头可怕的{spawn}，名叫{name}，出没于{location}。',
BOSS_TITLE:'怪物：{name}',
DESC_ITEM_LIGHT:'此武器主要受[BLUE]敏捷[]加成。详见属性窗口。',
DESC_ITEM_2HANDED:'此武器需要双手使用。',
DESC_ITEM_OFFHAND_ORB:'此物品持于左手，使用双手武器时无法生效。',
KEYBOARD_ATTACK_TEXT:'"通常你会用鼠标攻击，但它对远程战斗也很有用。攻击当前朝向上最近的敌人；若面前无人，会自动锁定射程内最近的敌人。"',
KEYBOARD_INTERACT_TEXT:'与附近的人物和物品互动（图标显示在右上角）。开启容器时也可"全部拿取"。',
HELP_SECTION_MOVEMENT:'提示：移动方式',
HELP_MOVEMENT:'欢迎来到王国，冒险者！移动主要靠鼠标。<p><p>两种方式：[BLUE]左键点击某处[]走向那里，或[BLUE]按住左键[]持续移动。',
HELP_SECTION_ATTACK_DESKTOP:'提示：战斗！',
HELP_ATTACK_DESKTOP:'攻击敌人有两种方式，视情况你多半会[BLUE]两者都用[]。<p><p>  »[BLUE]鼠标：[] 左键点击敌人进行攻击。可以按住鼠标持续攻击。<p><p>  »[BLUE]空格键：[] 自动转身并攻击最近的敌人（限武器射程内！）。远程战斗、或被敌人贴身没时间用鼠标瞄准时非常好用。',
HELP_INTERACTION_DESKTOP:'还记得他们教过你不要和陌生人说话、不要捡地上的东西吗？好吧，在这个游戏里你不但可以，而且还应该。<p><p>靠近人物或物品时，屏幕[BLUE]右上角[]会出现图标。[BLUE]按 TAB 键[]互动，或直接点击图标。',
HELP_SAVE_DESKTOP:'现在是[BLUE]保存游戏[]的好时机。《放逐王国》相当致命，所以经常存档！<p><p>按 [BLUE]F9 键[]快速存档，或按 [BLUE]Esc 后选择保存[]查看更多选项。记住，[BLUE]在地牢里[]，只有退出时才能存档。',
HELP_SAVE_DESKTOP_CASUAL:'现在是[BLUE]保存游戏[]的好时机。《放逐王国》相当致命，所以经常存档！<p><p>按 [BLUE]F9 键[]快速存档，或按 [BLUE]Esc 后选择保存[]查看更多选项。',
WARNING_TRANSLATION_ALMOST:'游戏中新增的部分内容可能尚未翻译，将以英文显示。翻译会尽快补上。',
HELP_ATTACK_DESKTOP2:'攻击敌人有两种方式，视情况你多半会[BLUE]两者都用[]。<p><p>  »[BLUE]鼠标：[] 左键点击敌人进行攻击。可以按住鼠标持续攻击。<p><p>  »[BLUE]空格键：[] 自动转身并攻击最近的敌人（限武器射程内！）。远程战斗、或被敌人贴身没时间用鼠标瞄准时非常好用。',
BACKUP_INFO_DESKTOP:'你可以从文件导入/导出存档。可用于备份，或在不同的安装之间转移数据。要恢复文件，请确保它存在于 [BLUE]##BACKUP##[]。',
DESC_ITEM_RANGED:'此武器可以进行远程攻击。',
RES_CHANGE:'提醒：分辨率更改将在重启游戏后生效。',
DIF_LOWERED:'难度已降低。不过部分改动需要你在客栈睡觉重置区域后才会生效。',
DL_DESC_STORY:'与"休闲"相同，但恢复更强、敌人更弱。散步模式。',
CONFIRM_RELOAD:'确定要读取存档并放弃当前游戏吗？',
CONFIRM_OVERWRITE:'确定要用新存档覆盖这个存档吗？',
CANT_SAVE_ENEMIES:'无法在此保存游戏：附近有敌人。找个安全的地方！',
CANT_SAVE_INDOOR:'无法在此区域保存游戏。',
CANT_SAVE_HEALTH:'无法保存游戏：你的生命值太低！请先治疗，或在客栈睡觉。',
RED_DIFFICULTY_CONFIRM:'确定要降低此游戏的难度吗？',
};
delete zh.DESC_AGA_PLACEHOLDER_;

const path = process.argv[2];
let text = fs.readFileSync(path, 'utf8');
const lines = text.split('\r\n');
let changed = 0, missed = [];
const out = lines.map((line) => {
  if (!line.trim()) return line;
  const cols = line.split('\t');
  const tag = cols[0].trim();
  if (zh[tag] !== undefined) {
    cols[3] = zh[tag];
    changed++;
    return cols.join('\t');
  }
  if (tag !== 'tag') missed.push(tag);
  return line;
});
fs.writeFileSync(path, out.join('\r\n'), 'utf8');
console.log(`updated ${changed} tags`);
if (missed.length) console.log('NOT TRANSLATED:', missed.join(', '));
